services:
  db:
    image: postgres:16
    container_name: eco_db
    environment:
      POSTGRES_DB: eco
      POSTGRES_USER: eco
      POSTGRES_PASSWORD: eco
    ports:
      - "5432:5432"
    volumes:
      - eco_pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eco -d eco"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build: .
    container_name: eco_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://eco:eco@db:5432/eco?sslmode=disable
      PORT: "8080"
      BLOCKCHAIN_RPC_URL: https://ethereum-sepolia-rpc.publicnode.com
      BLOCKCHAIN_CONTRACT: 0xd76b0A76141f54c867e19d4C9bE56AA12C4ed526
      BLOCKCHAIN_PRIVATE_KEY: e9d532007ca40b2f66b07b0277cc9df87edc3976f3fbe105a7004c010a958c97
    ports:
      - "8080:8080"

  simulator:
    build: ./simulator
    container_name: eco_simulator
    depends_on:
      - api

  frontend:
    build: ./frontend
    container_name: eco_frontend
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  eco_pgdata: